smithy.yml
=> EPL-822: adding smithy.yml back for internal build process and associated compliance checking

.gitignore, README.md, aws_lambda_fsm/aws.py, aws_lambda_fsm/constants.py, requirements_dev.txt, settings.py.example, tests/aws_lambda_fsm/test_aws.py
Added support for elasticache redis backend. 
@erinmichaeljohnson-wk @jasonbritton-wk
=> EPL-5903 Added support for redis elasticache engine

Makefile, README.md, aws_lambda_fsm/aws.py, aws_lambda_fsm/constants.py, aws_lambda_fsm/fsm.py, aws_lambda_fsm/handler.py, aws_lambda_fsm/utils.py, docs/AWS.md, docs/STEP.md, examples/tracer/actions.py, settings.py.example, tests/aws_lambda_fsm/test_aws.py, tests/aws_lambda_fsm/test_fsm.py, tests/docker/Dockerfile, tests/docker/settings.py.docker, tests/docker/supervisor.conf, tests/functional/__init__.py, tests/functional/actions.py, tests/functional/fsm.yaml, tests/functional/test_smoke.py, tests/functional/test_tracer.py, tests/functional/utils.py, tools/dev_lambda.py, tools/fsm_sqs_to_arn.py
Limited functional and/or acceptance testing in the project. Added a starting point.
@erinmichaeljohnson-wk @jasonbritton-wk
=> EPL-5854 Added some functional tests to run on travis-ci.org

aws_lambda_fsm/aws.py, aws_lambda_fsm/constants.py, settings.py.example, tests/aws_lambda_fsm/__init__.py, tests/aws_lambda_fsm/test_aws.py, tests/aws_lambda_fsm/test_fsm.py, tests/functional/Dockerfile, tests/functional/README.md, tests/functional/settings.py.docker, tests/functional/test_base.py
Added support for Redis replication groups over ssl and using passwords.
=> Redis password

aws_lambda_fsm/_pkg_meta.py
RELEASE aws-lambda-fsm-workflows 0.11.0
=> EPL-6214 RELEASE aws-lambda-fsm-workflows 0.11.0

aws_lambda_fsm/_pkg_meta.py
RELEASE aws-lambda-fsm-workflows 0.12.0
=> EPL-9744 RELEASE aws-lambda-fsm-workflows 0.12.0

aws_lambda_fsm/_pkg_meta.py, setup.py
=> EPL-9756 RELEASE aws-lambda-fsm 0.13.0

aws_lambda_fsm/_pkg_meta.py
RELEASE aws-lambda-fsm-workflows 0.14.0
@jasonbritton-wk
=> EPL-9757 RELEASE aws-lambda-fsm-workflows 0.14.0

aws_lambda_fsm/_pkg_meta.py
RELEASE aws-lambda-fsm-workflows 0.15.0
=> WAP-662 RELEASE aws-lambda-fsm-workflows 0.15.0

aws_lambda_fsm/_pkg_meta.py, setup.py
RELEASE aws-lambda-fsm-workflows 0.16.0
=> WAP-686 RELEASE aws-lambda-fsm-workflows 0.16.0

aws_lambda_fsm/_pkg_meta.py
RELEASE aws-lambda-fsm-workflows 0.0.17
=> WAP-687 RELEASE aws-lambda-fsm-workflows 0.0.17

aws_lambda_fsm/_pkg_meta.py, aws_lambda_fsm/constants.py, aws_lambda_fsm/handler.py, tests/aws_lambda_fsm/test_handler.py
RELEASE aws-lambda-fsm-workflows 0.18.0
=> WAP-974 RELEASE aws-lambda-fsm-workflows 0.18.0

aws_lambda_fsm/_pkg_meta.py
RELEASE aws-lambda-fsm-workflows 0.19.0
=> WAP-982 RELEASE aws-lambda-fsm-workflows 0.19.0

aws_lambda_fsm/constants.py, aws_lambda_fsm/handler.py, tests/aws_lambda_fsm/test_handler.py
redacting (potentially) user entered data in critical error cases as well
=> WAP-1018: redacting (potentially) user entered data in critical error cases as well

aws_lambda_fsm/_pkg_meta.py
RELEASE aws-lambda-fsm-workflows 0.20.0
=> WAP-998 RELEASE aws-lambda-fsm-workflows 0.20.0

aws_lambda_fsm/_pkg_meta.py
RELEASE aws-lambda-fsm-workflows 0.21.0
=> WAP-1032 RELEASE aws-lambda-fsm-workflows 0.21.0

.travis.yml, aws_lambda_fsm/aws.py, tests/aws_lambda_fsm/test_aws.py
Added public get_connection_info function.
=> WAP-1312 Added public get_connection_info function.

aws_lambda_fsm/_pkg_meta.py
RELEASE aws-lambda-fsm-workflows 0.22.0
=> WAP-1083 RELEASE aws-lambda-fsm-workflows 0.22.0

tools/dev_lambda.py
json fed into lambda command needs to be escaped properly
=> WAP-1591 json fed into lambda command needs to be escaped properly

aws_lambda_fsm/_pkg_meta.py
RELEASE aws-lambda-fsm-workflows 0.23.0
=> WAP-1361 RELEASE aws-lambda-fsm-workflows 0.23.0

.travis.yml, aws_lambda_fsm/config.py
=> WAP-2070 using safe_load instead

aws_lambda_fsm/aws.py, aws_lambda_fsm/constants.py, aws_lambda_fsm/fsm.py, tests/aws_lambda_fsm/test_aws.py, tests/aws_lambda_fsm/test_fsm.py
Added additional_delay_seconds to impose delay between state transitions, for throttling.
=> WAP-3791: added additional_delay_seconds to impose delay between state transitions, for throttling

aws_lambda_fsm/aws.py, aws_lambda_fsm/client.py, aws_lambda_fsm/fsm.py, aws_lambda_fsm/handler.py, aws_lambda_fsm/serialization.py, aws_lambda_fsm/utils.py, tests/aws_lambda_fsm/test_fsm.py, tests/aws_lambda_fsm/test_handler.py, tests/aws_lambda_fsm/test_serialization.py, tests/integration/actions.py, tests/integration/fsm.yaml, tests/integration/test_smoke.py, tests/integration/utils.py, tools/dev_lambda.py, tools/experimental/dev_ecs.py, tools/experimental/fsm_docker_runner.py, tools/start_state_machine.py, tools/yaml_to_json.py
Added a user-configurable serialization handler to provide developers a way to serialize exceptions, datetimes etc. in the user context.
=> WAP-4836 Added a user-configurable serialization handler.

aws_lambda_fsm/_pkg_meta.py
* [WAP-4836 Added a user-configurable serialization handler.](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/54)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.27.0...Workiva:release_aws-lambda-fsm-workflows_0.28.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.27.0...0.28.0
=> WAP-4775 Release aws-lambda-fsm-workflows 0.28.0

aws_lambda_fsm/client.py, tests/aws_lambda_fsm/test_client.py
Added `additional_delay_seconds` kwarg to the client api.
=> WAP-6270 Added additional_delay_seconds kwarg to the client api

aws_lambda_fsm/aws.py
adding some additional debugging to diagnose infrequent leasing errors
=> WAP-7223 adding some additional debugging to diagnose infrequent leasing errors

aws_lambda_fsm/aws.py, aws_lambda_fsm/constants.py, aws_lambda_fsm/fsm.py, tests/aws_lambda_fsm/test_fsm.py, tests/integration/actions.py, tests/integration/fsm.yaml, tests/integration/test_smoke.py, tests/integration/utils.py
lease timeout can be configured via system context of settings, depending on use case
=> WAP-7223 added ability to configure lease timeout

aws_lambda_fsm/handler.py
Some of these logs are a little noisy once you've gotten your code working. Consumers have the ability to log the context themselves if desired.
@shawnrusaw-wf
=> INFENG-12733 Change some logs to debug

aws_lambda_fsm/constants.py, aws_lambda_fsm/fsm.py, aws_lambda_fsm/transition.py, tests/aws_lambda_fsm/test_fsm.py, tests/integration/actions.py, tests/integration/fsm.yaml, tests/integration/test_smoke.py
added support for local dispatch, which does not enqueue more messages
=> WAP-9234 added support for local dispatch, which does not enqueue more messages

aws_lambda_fsm/fsm.py, tests/integration/test_smoke.py, tests/integration/utils.py
additional tests for local transitions
=> WAP-9328 additional tests for local transitions

aws_lambda_fsm/constants.py, aws_lambda_fsm/handler.py, tests/aws_lambda_fsm/test_handler.py, tests/integration/utils.py
passing along the lambda context in the volatile data
=> WAP-9455: passing along the lambda context in the volatile data
