Workiva/aws-lambda-fsm-workflows

smithy.yml

In order to keep builds deterministic, and reduce the risk of future build failure, please pin your smithy runner to the currently defaulted runner.
For more information please see the email 'Smithy Runner Recommendation' or reach out to Travis Reed in hipchat.
Requested by: @travisreed-wf

RMCONS-5518 Consume smithy-runner 3.5.5

---

aws_lambda_fsm/_pkg_meta.py
requirements.txt
requirements_dev.txt

Because lambda provides a version of boto3, we should move the dependency to the dev requirements so that it can be ran locally. Having it hard pinned in the requirements.txt, restricts the ability to use other libraries that do not support that version.

Move boto3 to a dev dependency

---

.gitignore
Makefile
aws_lambda_fsm/aws.py
aws_lambda_fsm/constants.py
tests/aws_lambda_fsm/test_aws.py

`_validate_elasticache_endpoints()` was out of sync

fixed _validate_elasticache_endpoints() since it was missed in the last release

---

aws_lambda_fsm/constants.py
aws_lambda_fsm/handler.py
tests/aws_lambda_fsm/test_handler.py

1. added AWS Lambda record to the `obj` (volatile) map

WAP-997: Added lambda event to the volatile map

---

aws_lambda_fsm/aws.py

missing checkpoint config is not a critical error

WAP-1029: missing checkpoint config is not a critical error

---

aws_lambda_fsm/_pkg_meta.py

* [WAP-3791: added additional_delay_seconds to impose delay between state transitions, for throttling](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/48)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.24.0...Workiva:release_aws-lambda-fsm-workflows_0.25.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.24.0...0.25.0

WAP-2415 Release aws-lambda-fsm-workflows 0.25.0

---

aws_lambda_fsm/aws.py
tests/aws_lambda_fsm/test_aws.py

Handling `None` context in `send_next_event_for_dispatch`.

WAP-3813: Handling None context in send_next_event_for_dispatch.

---

aws_lambda_fsm/_pkg_meta.py

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.25.0...Workiva:release_aws-lambda-fsm-workflows_0.26.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.25.0...0.26.0

WAP-3810 Release aws-lambda-fsm-workflows 0.26.0

---

aws_lambda_fsm/aws.py
settings.py.example
tests/aws_lambda_fsm/__init__.py
tests/aws_lambda_fsm/test_aws.py

1. added ability to inject additional kwargs into the boto3 client function

WAP-4774: added support for disabling ssl verification to make working with localstack easier

---

aws_lambda_fsm/_pkg_meta.py

* [WAP-4774: added support for disabling ssl verification to make working with localstack easier](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/52)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.26.0...Workiva:release_aws-lambda-fsm-workflows_0.27.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.26.0...0.27.0

WAP-3814 Release aws-lambda-fsm-workflows 0.27.0

---

aws_lambda_fsm/aws.py
tests/aws_lambda_fsm/test_aws.py

using sha256 rather than md5 in order to minimize the chances of future fedramp-related-scan warning messages
@oliverjensen-wk fyi

WAP-5316 using sha256 rather than md5 in order to minimize the chances of future fedramp-related-scan warning messages

---

aws_lambda_fsm/_pkg_meta.py

* [WAP-5158 Add Pyton 3 support](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/30)
* [WAP-5314 bumped the copyright to 2020](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/56)
* [WAP-5315 bumped pyyaml to 5.3 due to CVE](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/57)
* [WAP-5316 using sha256 rather than md5 in order to minimize the chances of future fedramp-related-scan warning messages](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/58)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.28.0...Workiva:release_aws-lambda-fsm-workflows_0.29.0
Diff Between Last Tag and New Tag: …

WAP-4860 Release aws-lambda-fsm-workflows 0.29.0

---

aws_lambda_fsm/_pkg_meta.py

* [WAP-5330 Removing dist folder](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/60)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.29.0...Workiva:release_aws-lambda-fsm-workflows_0.30.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.29.0...0.30.0

WAP-5327 Release aws-lambda-fsm-workflows 0.30.0

---

aws_lambda_fsm/_pkg_meta.py

* [WAP-5612 added .travis.yml setting to only deploy once, and added better description to pypi](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/62)
* [Add Dependabot to repository for automatic package updates](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/63)
* [WAP-6270 Added additional_delay_seconds kwarg to the client api](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/64)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.30.0...Workiva:release_aws-lambda-fsm-workflows_0.31.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.30.0...0.31.0
The logs for the request that …

WAP-5331 Release aws-lambda-fsm-workflows 0.31.0

---

aws_lambda_fsm/_pkg_meta.py

* [chore(deps-dev): bump boto from 2.40.0 to 2.49.0](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/70)
* [fix(deps): bump pyyaml from 5.3 to 5.3.1](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/72)
* [WAP-7223 adding some additional debugging to diagnose infrequent leasing errors](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/81)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.31.0...Workiva:release_aws-lambda-fsm-workflows_0.32.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.31.0...0.32.0
The logs for the request that created this PR can be found …

WAP-6271 Release aws-lambda-fsm-workflows 0.32.0

---

aws_lambda_fsm/_pkg_meta.py

* [WAP-7223 added ability to configure lease timeout](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/84)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.32.0...Workiva:release_aws-lambda-fsm-workflows_0.33.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.32.0...0.33.0

WAP-7229 Release aws-lambda-fsm-workflows 0.33.0

---

aws_lambda_fsm/_pkg_meta.py

* [INFENG-12733 Change some logs to debug](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/101)
* [WAP-9234 added support for local dispatch, which does not enqueue more messages](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/107)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.33.0...Workiva:release_aws-lambda-fsm-workflows_0.34.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.33.0...0.34.0

WAP-7241 Release aws-lambda-fsm-workflows 0.34.0

---

aws_lambda_fsm/_pkg_meta.py

* [WAP-9328 additional tests for local transitions](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/109)
* [WAP-9455: passing along the lambda context in the volatile data](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/112)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.34.0...Workiva:release_aws-lambda-fsm-workflows_0.35.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.34.0...0.35.0

WAP-9325 Release aws-lambda-fsm-workflows 0.35.0

---

requirements.txt
tests/functional/settings.py.functional

https://jira.atl.workiva.net/browse/SRE-28865
Amazon is is removing the vendored version of the requests library in botocore.  https://aws.amazon.com/es/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/
Update per linkded blog.

SRE-28865 removing vendored versions of requests from botocore

---

tests/functional/settings.py.functional

[SRE-29508](https://jira.atl.workiva.net/browse/SRE-29508)
AWS is deprecating the botocore vendored `requests` package. More info [here](https://aws.amazon.com/blogs/compute/upcoming-changes-to-the-python-sdk-in-aws-lambda/).
Replace references to the botocore vendored package with references to the `requests` package itself. Most of the work was already done by #134. This PR replaces the remaining reference to the vendored package.

SRE-29508 Replace vendored requests in functional test

---

aws_lambda_fsm/_pkg_meta.py

* [SRE-28865 removing vendored versions of requests from botocore](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/134)
* [SRE-29508 Replace vendored requests in functional test](https://github.com/Workiva/aws-lambda-fsm-workflows/pull/143)
Requested by: @matthewkeefer-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.35.0...Workiva:release_aws-lambda-fsm-workflows_0.36.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/aws-lambda-fsm-workflows/compare/0.35.0...0.36.0
This pull request can be recreated by clicking …

WAP-9456 Release aws-lambda-fsm-workflows 0.36.0
